try {
  // statements to be tested for errors
  console.log(wow)
}
catch (error) {
  // custom error output
  console.log("You have an error here sir")
}
